services:
  db:
    image: ankane/pgvector
    container_name: buddy-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - buddy_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  buddy_db_data:
